codecov:
  ci:
  - github.com
comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: no
  require_changes: false
  require_head: no
coverage:
  status:
    patch:
      default:
        informational: true
        only_pulls: false
        target: auto
        
    project:
      default:
        informational: true
        only_pulls: false
        target: auto
        

github_checks:
  annotations: true
