site_name: JijBenchmark's class reference

nav:
# rest of the navigation...
# defer to gen-files + literate-nav
- Code Reference: reference/  # 


theme:
  name: material
  palette:
    primary: indigo

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
          selection:
            docstring_style: "google"

markdown_extensions:
  - pymdownx.superfences

