name: Upload documentation

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-mkdocs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name : Install dependencies
      run: | 
        set -eux
        echo "Installing dependencies"
        python -m poetry install --only=main --only=docs
    - name: Docs build
      run: |
        set -eux
        echo "Building docs"
        poetry run mkdocs build --verbose --clean
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
