name: Upload documentation

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only=main --only=mkdocs
    - name: Docs build
      run: poetry run mkdocs build --verbose --clean --strict
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
